### ISSUE TITLE
Proposal: Could be wrapped under a framework

### ISSUE THREAD

**Issue by therealansh** [ecelliiitsonepat/ecelliiitsonepat.github.io#1]
The project only works with pure html and css can we do a workaround for wrapping this project under a framework like React or Next.js? This would help students to work with newer frameworks and tech stack. And if it is a static site we could actually use Hugo or Sapper.js, that would accelerate the development phase.

**Comment by VermaShivansh** [comment]
Yeah, we will be doing it soon as we learn the so.
